# Generated by Django 5.1.2 on 2024-12-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('background_skills', models.JSONField(default=[])),
                ('languages', models.JSONField(default=[])),
                ('instruments_prof', models.JSONField(default=[])),
                ('background_gear', models.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
                ('hp_dice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('pros', models.JSONField(default={})),
                ('cons', models.JSONField(default={})),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class_skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndpage.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Current_class_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndpage.class_skills')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=40)),
                ('level', models.IntegerField()),
                ('alignment', models.CharField(max_length=2)),
                ('experience', models.JSONField(default=[])),
                ('stats', models.JSONField(default={})),
                ('skills', models.JSONField(default={})),
                ('gear', models.JSONField(default={})),
                ('background_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndpage.background')),
                ('class_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndpage.current_class_info')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndpage.races')),
            ],
        ),
    ]
