# Generated by Django 5.1.2 on 2024-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_skills',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='hit_points',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='races',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
