# Generated by Django 5.1.2 on 2024-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpage', '0002_class_skills_description_player_hit_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_skills',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
