# Generated by Django 5.1.2 on 2024-12-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndpage', '0004_alter_class_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_skills',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
